-- Add multi-channel temp-probe (WN34/WN34S ITEM_TF_USR) columns to an existing PostgreSQL table.
-- Usage: psql -U postgres -d weather -f docs/sql-examples/alter-add-tf-postgres.sql

ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_temp_ch1 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_temp_ch2 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_temp_ch3 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_temp_ch4 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_temp_ch5 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_temp_ch6 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_temp_ch7 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_temp_ch8 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_battery_ch1 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_battery_ch2 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_battery_ch3 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_battery_ch4 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_battery_ch5 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_battery_ch6 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_battery_ch7 DOUBLE PRECISION;
ALTER TABLE wx_records ADD COLUMN IF NOT EXISTS tf_battery_ch8 DOUBLE PRECISION;
